fn main() {const TAPE_SIZE : usize = 30000 ; use std :: num :: Wrapping ; use std :: io
    :: { Read, Write, stdin, stdout } ; let mut next_char = [0 ; 1] ; let mut tape
    = [Wrapping (0u8) ; TAPE_SIZE] ; let mut ptr = 0 ; let mut pos = 0 ;ptr += 1 ;tape [ptr] -= Wrapping (1) ;ptr += 1 ;tape [ptr] += Wrapping (1) ;while tape [ptr] != Wrapping (0){ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;while tape [ptr] != Wrapping (0){tape [ptr] -= Wrapping (1) ;ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;ptr -= 1 ;ptr -= 1 ;ptr -= 1 ;}ptr += 1 ;tape [ptr] += Wrapping (1) ;stdout () . write_fmt (format_args ! ("{}", tape [ptr] . 0 as char)) . expect
    ("Error writing to output") ; stdout () . flush () . expect
    ("Error flushing output") ;ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;stdout () . write_fmt (format_args ! ("{}", tape [ptr] . 0 as char)) . expect
    ("Error writing to output") ; stdout () . flush () . expect
    ("Error flushing output") ;ptr += 1 ;tape [ptr] -= Wrapping (1) ;tape [ptr] -= Wrapping (1) ;tape [ptr] -= Wrapping (1) ;tape [ptr] -= Wrapping (1) ;tape [ptr] -= Wrapping (1) ;stdout () . write_fmt (format_args ! ("{}", tape [ptr] . 0 as char)) . expect
    ("Error writing to output") ; stdout () . flush () . expect
    ("Error flushing output") ;ptr -= 1 ;ptr -= 1 ;ptr -= 1 ;ptr -= 1 ;ptr -= 1 ;tape [ptr] += Wrapping (1) ;}ptr -= 1 ;while tape [ptr] != Wrapping (0){ptr += 1 ;while tape [ptr] != Wrapping (0){tape [ptr] -= Wrapping (1) ;}ptr += 1 ;while tape [ptr] != Wrapping (0){tape [ptr] -= Wrapping (1) ;}ptr += 1 ;while tape [ptr] != Wrapping (0){tape [ptr] -= Wrapping (1) ;}ptr -= 1 ;ptr -= 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;while tape [ptr] != Wrapping (0){tape [ptr] -= Wrapping (1) ;ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;ptr -= 1 ;ptr -= 1 ;}ptr += 1 ;tape [ptr] += Wrapping (1) ;stdout () . write_fmt (format_args ! ("{}", tape [ptr] . 0 as char)) . expect
    ("Error writing to output") ; stdout () . flush () . expect
    ("Error flushing output") ;ptr += 1 ;tape [ptr] += Wrapping (1) ;tape [ptr] += Wrapping (1) ;stdout () . write_fmt (format_args ! ("{}", tape [ptr] . 0 as char)) . expect
    ("Error writing to output") ; stdout () . flush () . expect
    ("Error flushing output") ;ptr -= 1 ;ptr -= 1 ;}}